alias nano='micro'
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias zgrep='zgrep --color=auto'
alias ll='ls -l'
alias la='ls -lA'
alias lla="ls -A"
alias sls='screen -ls | ntab -t 2 | colr -y Attached'
