preload = ~/.config/hypr/images/bg2560x1440.png
preload = ~/.config/hypr/images/bg1920x1080.png

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/images/bg2560x1440.png
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/images/bg1920x1080.png
}

splash = false
