source = ~/.config/hypr/land/monitors.conf
source = ~/.config/hypr/land/vars.conf
source = ~/.config/hypr/land/autostart.conf
source = ~/.config/hypr/land/look.conf
source = ~/.config/hypr/land/input.conf
source = ~/.config/hypr/land/window.conf

source = ~/.config/hypr/land/local.conf
