[window]
opacity = 0.8
padding.x = 10
padding.y = 5
dynamic_padding = true

[font]
normal = { family = "monospace", style = "Regular" }
#normal = { family = "Overpass Mono", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
size = 12
builtin_box_drawing = true

[colors.primary]
foreground = "#cccccc"
background = "#000000"

[colors.normal]
black   = "#000000"
red     = "#cc0000"
green   = "#00cc00"
yellow  = "#cccc00"
blue    = "#0077cc"
magenta = "#cc00cc"
cyan    = "#00cccc"
white   = "#999999"

[colors.bright]
black   = "#333333"
red     = "#cc7777"
green   = "#77ff77"
yellow  = "#cccc99"
blue    = "#7799cc"
magenta = "#cc77cc"
cyan    = "#77cccc"
white   = "#cccccc"


# path hints, and require ctrl
[[hints.enabled]]
	regex = "(?:(?:https?|git|mailto|ftp|ssh)://[^\\s<>\"'()]+)|(?:(?:~/|/|\\./|\\.\\./)[^\\s<>\"'()]+)"
	command = "xdg-open"
	post_processing = true
	binding = { key = "U", mods = "Control|Shift" }
	mouse = { enabled = true, mods = "Control" }
