
general {
	gaps_in = 0
	gaps_out = 0
	border_size = 0
	resize_on_border = false
	allow_tearing = false
	layout = dwindle
}
debug {
    damage_tracking = 0
}
decoration {
	# screen_shader = shaders/bloom.frag
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled = false
    }
    blur {
        enabled = true
        size = 3
        passes = 3
    }
}

animations {
    enabled = no
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

windowrule = match:class ^(immy)$, float on, no_blur on
