exec-once = ~/.config/hyprland/portal-reset.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets

{ENABLE_WALL}exec-once = hyprpaper
{ENABLE_LOCK}exec-once = hyprlock
{ENABLE_IDLE}exec-once = hypridle
{ENABLE_STAT}exec-once = waybar
