windowrule = match:class ^(immy)$, float on, no_blur on

windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on
